In [1]:
import numpy as np

In [2]:
arr_2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
num=np.linspace(0,1,5)
num

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
arr1=np.array([10,20,30])
arr2=np.array([40,50,60,70,80,90])
arr3=np.append(arr1,arr2)
arr3

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [9]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
for val in np.nditer(arr):
    print(val)

1
2
3
4
5
6
7
8
9
10
11
12


In [10]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
for ind,val in np.ndenumerate(arr):
    print(ind, val)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
(2, 0) 9
(2, 1) 10
(2, 2) 11
(2, 3) 12
